version: "2"
services:
 app:
  build: ./
  restart: always
  # Ignore editor syntax errors. Produces valid YAML
  environment:{{range $key, $value := .}}
      - {{$key}}{{end}}
  ports:
  - "6001:6081"
