name: Test CLI action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          image: |
            docker.io/minhngocnguyen/auth-service

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Show version
        id: show_version
        run: echo "${{steps.meta.outputs.tags}}"
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
      #     build-args: DOPPLER_TOKEN=${{secrets.DOPPLER_TOKEN}}
