name: Test CLI action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Read current version
        id: read_version
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Increment version
        id: increment_version
        run: echo "::set-output name=version::$(./increment_version.sh ${{ steps.read_version.outputs.version }})"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Show version
        id: show_version
        run: echo "${{steps.increment_version.outputs.version}}"
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
      #     build-args: DOPPLER_TOKEN=${{secrets.DOPPLER_TOKEN}}
